const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  send: (prompt) => ipcRenderer.invoke('llm:send', prompt),
  getCwd: () => ipcRenderer.invoke('cwd:get'),
  setCwd: (dir) => ipcRenderer.invoke('cwd:set', dir),
  pickDir: () => ipcRenderer.invoke('cwd:pick'),
  newSession: () => ipcRenderer.invoke('session:new'),
  listSessions: () => ipcRenderer.invoke('sessions:list'),
  resolveProject: (key) => ipcRenderer.invoke('project:resolve', key),
  resumeSession: (id) => ipcRenderer.invoke('session:resume', id),
  deleteSession: (id) => ipcRenderer.invoke('session:delete', id),
  deleteAllSessions: () => ipcRenderer.invoke('session:delete-all'),
  sessionHistory: (id) => ipcRenderer.invoke('session:history', id),
  termCreate: () => ipcRenderer.invoke('term:create'),
  termWrite: (tabId, data) => ipcRenderer.send('term:write', tabId, data),
  termResize: (tabId, cols, rows) => ipcRenderer.send('term:resize', tabId, cols, rows),
  termDestroy: (tabId) => ipcRenderer.send('term:destroy', tabId),
  onTermData: (cb) => ipcRenderer.on('term:data', (_e, tabId, d) => cb(tabId, d)),
  onTermExit: (cb) => ipcRenderer.on('term:exit', (_e, tabId) => cb(tabId)),
  onChunk: (cb) => ipcRenderer.on('llm:chunk', (_e, d) => cb(d)),
  onThinking: (cb) => ipcRenderer.on('llm:thinking', (_e, d) => cb(d)),
  onText: (cb) => ipcRenderer.on('llm:text', (_e, d) => cb(d)),
  onSession: (cb) => ipcRenderer.on('llm:session', (_e, id) => cb(id)),
  onDone: (cb) => ipcRenderer.on('llm:done', (_e, c) => cb(c)),
  onError: (cb) => ipcRenderer.on('llm:error', (_e, m) => cb(m)),
  onTimeout: (cb) => ipcRenderer.on('llm:timeout', (_e, m) => cb(m)),
  onUsage: (cb) => ipcRenderer.on('llm:usage', (_e, u) => cb(u)),
  lspInitialize: () => ipcRenderer.invoke('lsp:initialize'),
  lspOpen: (filePath) => ipcRenderer.invoke('lsp:open', filePath),
  lspClose: (filePath) => ipcRenderer.invoke('lsp:close', filePath),
  lspChange: (filePath, text) => ipcRenderer.invoke('lsp:change', filePath, text),
  lspCompletion: (filePath, line, character) => ipcRenderer.invoke('lsp:completion', filePath, line, character),
  lspHover: (filePath, line, character) => ipcRenderer.invoke('lsp:hover', filePath, line, character),
  lspDefinition: (filePath, line, character) => ipcRenderer.invoke('lsp:definition', filePath, line, character),
  lspReferences: (filePath, line, character) => ipcRenderer.invoke('lsp:references', filePath, line, character),
  lspDiagnostics: (filePath) => ipcRenderer.invoke('lsp:diagnostics', filePath),
  lspAllDiagnostics: () => ipcRenderer.invoke('lsp:all-diagnostics'),
  onLspDiagnostics: (cb) => ipcRenderer.on('lsp:diagnostics', (_e, d) => cb(d)),
  onLspReady: (cb) => ipcRenderer.on('lsp:ready', (_e, d) => cb(d)),
  readFile: (filePath) => ipcRenderer.invoke('file:read', filePath),
  snapshotFile: (filePath) => ipcRenderer.invoke('file:snapshot', filePath),
  computeDiff: (before, after) => ipcRenderer.invoke('diff:compute', before, after),
  listDir: (dirPath) => ipcRenderer.invoke('file:list-dir', dirPath),
  pickFile: () => ipcRenderer.invoke('file:pick'),
  onDiff: (cb) => ipcRenderer.on('llm:diff', (_e, d) => cb(d)),
  onFileWrite: (cb) => ipcRenderer.on('llm:file-write', (_e, d) => cb(d)),
});
