const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  send: (prompt) => ipcRenderer.invoke('llm:send', prompt),
  getCwd: () => ipcRenderer.invoke('cwd:get'),
  getModel: () => ipcRenderer.invoke('model:get'),
  setModel: (model) => ipcRenderer.invoke('model:set', model),
  listModels: () => ipcRenderer.invoke('model:list'),
  saveAuth: (provider, key) => ipcRenderer.invoke('auth:save', provider, key),
  listAuth: () => ipcRenderer.invoke('auth:list'),
  forgetAuth: (provider) => ipcRenderer.invoke('auth:forget', provider),
  setCwd: (dir) => ipcRenderer.invoke('cwd:set', dir),
  pickDir: () => ipcRenderer.invoke('cwd:pick'),
  newSession: () => ipcRenderer.invoke('session:new'),
  listSessions: () => ipcRenderer.invoke('sessions:list'),
  resolveProject: (key) => ipcRenderer.invoke('project:resolve', key),
  resumeSession: (id) => ipcRenderer.invoke('session:resume', id),
  deleteSession: (id) => ipcRenderer.invoke('session:delete', id),
  deleteAllSessions: () => ipcRenderer.invoke('session:delete-all'),
  renameSession: (id, title) => ipcRenderer.invoke('session:rename', id, title),
  sessionHistory: (id) => ipcRenderer.invoke('session:history', id),
  termCreate: () => ipcRenderer.invoke('term:create'),
  termWrite: (tabId, data) => ipcRenderer.send('term:write', tabId, data),
  termResize: (tabId, cols, rows) => ipcRenderer.send('term:resize', tabId, cols, rows),
  termDestroy: (tabId) => ipcRenderer.send('term:destroy', tabId),
  onTermData: (cb) => ipcRenderer.on('term:data', (_e, tabId, d) => cb(tabId, d)),
  onTermExit: (cb) => ipcRenderer.on('term:exit', (_e, tabId) => cb(tabId)),
  onChunk: (cb) => ipcRenderer.on('llm:chunk', (_e, d) => cb(d)),
  onThinking: (cb) => ipcRenderer.on('llm:thinking', (_e, d) => cb(d)),
  onThinkingReset: (cb) => ipcRenderer.on('llm:thinking-reset', (_e, ts) => cb(ts)),
  onThinkingEnd: (cb) => ipcRenderer.on('llm:thinking-end', (_e, ts) => cb(ts)),
  onText: (cb) => ipcRenderer.on('llm:text', (_e, d) => cb(d)),
  onSession: (cb) => ipcRenderer.on('llm:session', (_e, id, model) => cb(id, model)),
  onDone: (cb) => ipcRenderer.on('llm:done', (_e, c) => cb(c)),
  onError: (cb) => ipcRenderer.on('llm:error', (_e, m) => cb(m)),
  onTimeout: (cb) => ipcRenderer.on('llm:timeout', (_e, m) => cb(m)),
  onLog: (cb) => ipcRenderer.on('llm:log', (_e, d) => cb(d)),
  onUsage: (cb) => ipcRenderer.on('llm:usage', (_e, u) => cb(u)),
  onTitleGenerated: (cb) => ipcRenderer.on('session:title-generated', (_e, title) => cb(title)),
  lspInitialize: () => ipcRenderer.invoke('lsp:initialize'),
  lspOpen: (filePath) => ipcRenderer.invoke('lsp:open', filePath),
  lspClose: (filePath) => ipcRenderer.invoke('lsp:close', filePath),
  lspChange: (filePath, text) => ipcRenderer.invoke('lsp:change', filePath, text),
  lspCompletion: (filePath, line, character) => ipcRenderer.invoke('lsp:completion', filePath, line, character),
  lspHover: (filePath, line, character) => ipcRenderer.invoke('lsp:hover', filePath, line, character),
  lspDefinition: (filePath, line, character) => ipcRenderer.invoke('lsp:definition', filePath, line, character),
  lspReferences: (filePath, line, character) => ipcRenderer.invoke('lsp:references', filePath, line, character),
  lspDiagnostics: (filePath) => ipcRenderer.invoke('lsp:diagnostics', filePath),
  lspAllDiagnostics: () => ipcRenderer.invoke('lsp:all-diagnostics'),
  onLspDiagnostics: (cb) => ipcRenderer.on('lsp:diagnostics', (_e, d) => cb(d)),
  onLspReady: (cb) => ipcRenderer.on('lsp:ready', (_e, d) => cb(d)),
  readFile: (filePath) => ipcRenderer.invoke('file:read', filePath),
  snapshotFile: (filePath) => ipcRenderer.invoke('file:snapshot', filePath),
  computeDiff: (before, after) => ipcRenderer.invoke('diff:compute', before, after),
  listDir: (dirPath) => ipcRenderer.invoke('file:list-dir', dirPath),
  pickFile: () => ipcRenderer.invoke('file:pick'),
  onDiff: (cb) => ipcRenderer.on('llm:diff', (_e, d) => cb(d)),
  onFileWrite: (cb) => ipcRenderer.on('llm:file-write', (_e, d) => cb(d)),
  onFileTreeChanged: (cb) => ipcRenderer.on('file:tree-changed', (_e, d) => cb(d)),
  onCwdChanged: (cb) => ipcRenderer.on('cwd:changed', (_e, d) => cb(d)),
  gitRepoCheck: () => ipcRenderer.invoke('git:repo-check'),
  gitStatus: () => ipcRenderer.invoke('git:status'),
  gitDiffFile: (filePath, staged) => ipcRenderer.invoke('git:diff-file', filePath, staged),
  gitStage: (filePath) => ipcRenderer.invoke('git:stage', filePath),
  gitUnstage: (filePath) => ipcRenderer.invoke('git:unstage', filePath),
  gitStageAll: () => ipcRenderer.invoke('git:stage-all'),
  gitUnstageAll: () => ipcRenderer.invoke('git:unstage-all'),
  gitCommit: (message) => ipcRenderer.invoke('git:commit', message),
  gitBranches: () => ipcRenderer.invoke('git:branches'),
  gitCheckout: (branchName) => ipcRenderer.invoke('git:checkout', branchName),
  gitStashList: () => ipcRenderer.invoke('git:stash-list'),
  gitStashPop: (index) => ipcRenderer.invoke('git:stash-pop', index),
  gitStashSave: (message) => ipcRenderer.invoke('git:stash-save', message),
  gitLog: () => ipcRenderer.invoke('git:log'),
});
