import { useCallback, useEffect, useRef, useState } from 'react';
import { api } from '../api';
import type { SessionHistoryMessage, UsageData } from '../types/api';
import { isRecord } from '../lib/guards';

export interface ToolBlock {
  id: string;
  toolName: string;
  args: unknown;
  result: unknown;
  isError: boolean;
}

export interface ThinkingBlockData { thinking: string; duration: number }
export interface DiffEntry { filePath: string; relPath: string; diff: string }
export interface TodoTask { content: string; status: string }
export interface TodoPhase { name: string; tasks: TodoTask[] }

export type PlanRow =
  | { type: 'section'; text: string }
  | { type: 'item'; text: string; checked: boolean };

export interface SendOptions {
  isPlanMode?: boolean;
  isGeneratingDoc?: boolean;
  plannerDocType?: string;
}

// A document generated by the Plan Mode "Create Document" flow, ready for
// the caller (App.tsx) to persist into the Docs view and clear.
export interface GeneratedDocument { title: string; content: string }

export interface UsageState {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  contextTokens: number; // context-window occupancy as of the latest completed LLM call
  costUsd: number;       // cumulative USD spend across the whole session
}

export interface ChatMessage {
  role: 'user' | 'assistant' | 'error' | 'system';
  content: string;
  toolBlocks: ToolBlock[];
  thinking: string;
  thinkingBlocks: ThinkingBlockData[];
  diffs: DiffEntry[];
}

// Validates the `todo` tool's result.details payload (see main.js's
// tool_execution_end handler) into a clean snapshot for the todo panel.
// Always the FULL current list state, not a delta — safe to just replace.
function parseTodoPhases(details: unknown): TodoPhase[] | null {
  if (!isRecord(details) || !Array.isArray(details.phases)) return null;
  const phases: TodoPhase[] = [];
  for (const p of details.phases) {
    if (!isRecord(p) || typeof p.name !== 'string' || !Array.isArray(p.tasks)) continue;
    const tasks: TodoTask[] = [];
    for (const t of p.tasks) {
      if (isRecord(t) && typeof t.content === 'string' && typeof t.status === 'string') {
        tasks.push({ content: t.content, status: t.status });
      }
    }
    phases.push({ name: p.name, tasks });
  }
  return phases;
}

// Plan Mode's system prompt (see main.js's DOC_STANDARDS instruction) has the
// model re-emit the FULL outline — every "## " section heading and its
// "- [ ]"/"- [x]" items — on every turn. Re-parsing the whole accumulated
// turn text on each delta (rather than tracking incremental state) is both
// simpler and self-correcting if the model reorders or drops a section.
const PLAN_TODO_RE = /^[-*]\s+\[([ xX])\]\s+(.*)/;
const PLAN_HEADING_RE = /^#{1,6}\s+(.+?)\s*$/;

function parsePlanOutline(text: string): PlanRow[] {
  const rows: PlanRow[] = [];
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    const todoMatch = line.match(PLAN_TODO_RE);
    if (todoMatch) {
      rows.push({ type: 'item', text: todoMatch[2], checked: todoMatch[1].toLowerCase() === 'x' });
      continue;
    }
    const headingMatch = line.match(PLAN_HEADING_RE);
    if (headingMatch) rows.push({ type: 'section', text: headingMatch[1] });
  }
  return rows;
}

// Resolves the "Create Document" turn's final content: prefer a file the
// model actually wrote/edited (agentic models often save e.g. BRD.md via a
// tool call instead of emitting the document as chat text) over the
// streamed text, which may just be narration in that case. Falls back to a
// fenced ```markdown block if present, else the raw streamed text.
async function resolveGeneratedDocument(filePath: string | null, streamedText: string): Promise<string | null> {
  if (filePath) {
    try {
      const fileContent = await api.readFile(filePath);
      if (typeof fileContent === 'string' && fileContent.trim()) return fileContent.trim();
    } catch {
      // fall through to the streamed text
    }
  }
  const fenced = streamedText.match(/```(?:markdown|md)\n([\s\S]*?)```/i);
  const content = (fenced ? fenced[1] : streamedText).trim();
  return content || null;
}

// Formats a Date as "YYYY-MM-DD HH:mm:ss" (local time) for use in generated
// document titles — sortable and unambiguous without being as noisy as a
// full ISO string.
function formatTimestamp(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
}

const ZERO_USAGE: UsageState = { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, contextTokens: 0, costUsd: 0 };

// Normalizes one `llm:usage` payload into the fields the status bar needs,
// plus this call's own USD cost — callers accumulate that into a running
// session total (each usage event is a distinct completed LLM call, not an
// incremental streaming delta, so summing costs across events is safe).
function parseUsageEvent(u: UsageData): { usage: Omit<UsageState, 'costUsd'>; turnCost: number } {
  const inputTokens = typeof u.input === 'number' ? u.input : 0;
  const outputTokens = typeof u.output === 'number' ? u.output : 0;
  const cacheReadTokens = typeof u.cacheRead === 'number' ? u.cacheRead : 0;
  const cacheWriteTokens = typeof u.cacheWrite === 'number' ? u.cacheWrite : 0;
  const contextTokens = typeof u.totalTokens === 'number' ? u.totalTokens : inputTokens + outputTokens + cacheReadTokens + cacheWriteTokens;
  const turnCost = u.cost && typeof u.cost.total === 'number' ? u.cost.total : 0;
  return { usage: { inputTokens, outputTokens, cacheReadTokens, cacheWriteTokens, contextTokens }, turnCost };
}

export interface ChatState {
  messages: ChatMessage[];
  streaming: string;        // live assistant text buffer (md), empty when idle
  streamingTools: ToolBlock[]; // tool blocks accumulated during current turn
  streamingDiffs: DiffEntry[]; // before/after diffs produced during current turn
  thinking: string;          // live reasoning buffer
  busy: boolean;
  error: string | null;
  sessionId: string | null;
  todos: TodoPhase[]; // current todo list state, empty when no todo tool has been used
  usage: UsageState; // token/cost accounting for the status bar
  planMode: boolean;         // Plan Mode toggle — next send() plans a document instead of answering directly
  docType: string;           // 'BRD' | 'PRD' | 'Custom' — selected planning-doc standard (see main.js's DOC_STANDARDS)
  planRows: PlanRow[];       // live/finalized Plan Mode outline (sections + checklist items)
  pendingDocument: GeneratedDocument | null; // set once a "Create Document" turn finishes; caller persists + clears it
}

export interface UseChatReturn extends ChatState {
  send: (text: string, mentions?: string[], options?: SendOptions) => void;
  cancel: () => void;
  reset: () => void;
  loadHistory: (messages: SessionHistoryMessage[], initialUsage?: { input: number; output: number; totalTokens: number; costUsd: number }) => void;
  setPlanMode: (planMode: boolean) => void;
  setDocType: (docType: string) => void;
  togglePlanItem: (index: number) => void;
  generateDocument: () => void;
  clearPendingDocument: () => void;
}

let toolCounter = 0;

export function useChat(): UseChatReturn {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [streaming, setStreaming] = useState('');
  const [streamingTools, setStreamingTools] = useState<ToolBlock[]>([]);
  const [streamingDiffs, setStreamingDiffs] = useState<DiffEntry[]>([]);
  const [thinking, setThinking] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [todos, setTodos] = useState<TodoPhase[]>([]);
  const [usage, setUsage] = useState<UsageState>(ZERO_USAGE);
  const [planMode, setPlanMode] = useState(false);
  const [docType, setDocType] = useState('BRD');
  const [planRows, setPlanRows] = useState<PlanRow[]>([]);
  const [pendingDocument, setPendingDocument] = useState<GeneratedDocument | null>(null);

  // Refs so event handlers (registered once) always see latest state setters.
  const streamingRef = useRef('');
  const thinkingRef = useRef('');
  const costRef = useRef(0); // cumulative session spend; usage state derives from this each event
  const planStreamActiveRef = useRef(false);   // true while the current turn is streaming a Plan Mode outline
  const generatingDocRef = useRef(false);      // true while the current turn is generating the final document
  const generatingDocTypeRef = useRef('BRD');  // doc type label for the in-flight "Create Document" turn
  const generatingDocFileRef = useRef<string | null>(null); // file the model wrote during a "Create Document" turn, if any
  const sessionIdRef = useRef<string | null>(null); // mirrors `sessionId` state for use in callbacks with stale closures (e.g. finalize)

  // Wire all streaming events once.
  useEffect(() => {
    const unsubs = [
      api.onSession((id) => { sessionIdRef.current = id; setSessionId(id); }),
      api.onLlmBusy((v) => setBusy(v)),
      api.onThinkingReset(() => { setThinking(''); thinkingRef.current = ''; }),
      api.onThinking((delta) => {
        thinkingRef.current += String(delta ?? '');
        setThinking(thinkingRef.current);
      }),
      api.onThinkingEnd(() => { /* keep accumulated thinking visible */ }),
      api.onText((delta) => {
        streamingRef.current += String(delta ?? '');
        setStreaming(streamingRef.current);
        if (planStreamActiveRef.current) setPlanRows(parsePlanOutline(streamingRef.current));
      }),
      api.onToolCall((data) => {
        const toolName = (isRecord(data) && 'toolName' in data && typeof data.toolName === 'string') ? data.toolName : 'tool';
        const args = (isRecord(data) && 'args' in data) ? data.args : {};
        setStreamingTools((prev) => [...prev, {
          id: `t${toolCounter++}`,
          toolName,
          args,
          result: null,
          isError: false,
        }]);
      }),
      api.onToolResult((data) => {
        const result = (isRecord(data) && 'result' in data) ? data.result : null;
        const isError = isRecord(data) && 'isError' in data && data.isError === true;
        setStreamingTools((prev) => {
          if (prev.length === 0) return prev;
          const copy = prev.slice();
          const last = copy[copy.length - 1];
          copy[copy.length - 1] = { ...last, result, isError };
          return copy;
        });
        if (isRecord(data) && data.toolName === 'todo') {
          const phases = parseTodoPhases(data.details);
          if (phases) setTodos(phases);
        }
      }),
      api.onDiff((data) => {
        if (!isRecord(data) || typeof data.diff !== 'string') return;
        const diffText = data.diff;
        const filePath = typeof data.filePath === 'string' ? data.filePath : '';
        const relPath = typeof data.relPath === 'string' ? data.relPath : '';
        setStreamingDiffs((prev) => [...prev, { filePath, relPath, diff: diffText }]);
      }),
      api.onUsage((u) => {
        const { usage: parsed, turnCost } = parseUsageEvent(u);
        costRef.current += turnCost;
        setUsage({ ...parsed, costUsd: costRef.current });
      }),
      api.onError((msg) => {
        setError(msg);
        setBusy(false);
        finalize();
      }),
      api.onCancelled(() => {
        finalize();
      }),
      api.onDone(() => finalize()),
      api.onFileWrite((filePath) => {
        if (generatingDocRef.current && typeof filePath === 'string') generatingDocFileRef.current = filePath;
      }),
    ];
    return () => unsubs.forEach((u) => u());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const finalize = useCallback(() => {
    const text = streamingRef.current;
    const thoughtText = thinkingRef.current;
    const wasGeneratingDoc = generatingDocRef.current;
    const docTypeLabel = generatingDocTypeRef.current;
    const docFile = generatingDocFileRef.current;
    generatingDocRef.current = false;
    planStreamActiveRef.current = false;
    setStreamingTools((tools) => {
      setStreamingDiffs((diffs) => {
        setStreaming('');
        streamingRef.current = '';
        setThinking('');
        thinkingRef.current = '';
        if (text || tools.length || thoughtText || diffs.length) {
          setMessages((prev) => [...prev, {
            role: 'assistant',
            content: text,
            toolBlocks: tools,
            thinking: thoughtText,
            thinkingBlocks: [],
            diffs,
          }]);
        }
        return [];
      });
      return [];
    });
    if (wasGeneratingDoc) {
      void resolveGeneratedDocument(docFile, text).then((content) => {
        if (!content) return;
        // Tag the title with when it was generated and which session it came
        // from — generic "BRD Document" names collide across regenerations.
        const parts = [`${docTypeLabel} Document`, formatTimestamp(new Date())];
        if (sessionIdRef.current) parts.push(sessionIdRef.current);
        setPendingDocument({ title: parts.join(' — '), content });
      });
    }
  }, []);

  const send = useCallback((text: string, mentions: string[] = [], options?: SendOptions) => {
    if (!text.trim() || busy) return;
    setError(null);
    setMessages((prev) => [...prev, { role: 'user', content: text, toolBlocks: [], thinking: '', thinkingBlocks: [], diffs: [] }]);
    streamingRef.current = '';
    thinkingRef.current = '';
    setStreaming('');
    setThinking('');
    const plannerDocType = options?.plannerDocType ?? docType;
    planStreamActiveRef.current = !!options?.isPlanMode;
    generatingDocRef.current = !!options?.isGeneratingDoc;
    generatingDocTypeRef.current = plannerDocType;
    generatingDocFileRef.current = null;
    if (options?.isPlanMode) setPlanRows([]);
    api.send({
      text,
      mentions,
      isPlanMode: !!options?.isPlanMode,
      isGeneratingDoc: !!options?.isGeneratingDoc,
      plannerDocType,
    }).catch((e) => setError(String(e)));
  }, [busy, docType]);

  const cancel = useCallback(() => { api.cancel().catch(() => {}); }, []);

  const togglePlanItem = useCallback((index: number) => {
    setPlanRows((prev) => prev.map((row, i) => (i === index && row.type === 'item' ? { ...row, checked: !row.checked } : row)));
  }, []);

  // Mirrors the legacy Planner's "Create Document" button: groups the
  // approved outline by section (if the user checked specific items, only
  // those are included; otherwise the whole outline is), then asks the
  // model to expand it into the final document.
  const generateDocument = useCallback(() => {
    const anyChecked = planRows.some((r) => r.type === 'item' && r.checked);
    const groups: { title: string | null; items: string[] }[] = [];
    let current: { title: string | null; items: string[] } | null = null;
    for (const row of planRows) {
      if (row.type === 'section') {
        current = { title: row.text, items: [] };
        groups.push(current);
      } else if (!anyChecked || row.checked) {
        if (!current) { current = { title: null, items: [] }; groups.push(current); }
        current.items.push(row.text);
      }
    }
    const outline = groups
      .filter((g) => g.items.length > 0)
      .map((g) => (g.title ? `## ${g.title}\n` : '') + g.items.map((t) => `- ${t}`).join('\n'))
      .join('\n\n');
    setPlanMode(false);
    setPlanRows([]);
    send(`Please generate the final ${docType} document based on this approved plan outline:\n\n${outline}`, [], {
      isGeneratingDoc: true,
      plannerDocType: docType,
    });
  }, [planRows, docType, send]);

  const clearPendingDocument = useCallback(() => setPendingDocument(null), []);

  const reset = useCallback(() => {
    setMessages([]); setStreaming(''); setStreamingTools([]); setStreamingDiffs([]); setThinking(''); setError(null); setTodos([]);
    setUsage(ZERO_USAGE); costRef.current = 0;
    setPlanMode(false); setPlanRows([]); setPendingDocument(null);
    planStreamActiveRef.current = false; generatingDocRef.current = false; generatingDocFileRef.current = null;
  }, []);

  // Rebuilds ChatMessage[] from raw session:history events, in original
  // chronological order. A 'toolResult' event fills in the earliest still-
  // unresolved tool block of the current turn; a 'diff' event is appended to
  // the current turn's diffs (matching finalize()'s live grouping below); a
  // 'user' event flushes and starts a new turn.
  const loadHistory = useCallback((rawMessages: SessionHistoryMessage[], initialUsage?: { input: number; output: number; totalTokens: number; costUsd: number }) => {
    setStreaming(''); setStreamingTools([]); setStreamingDiffs([]); setThinking(''); setError(null);
    streamingRef.current = ''; thinkingRef.current = '';

    const result: ChatMessage[] = [];
    let latestTodos: TodoPhase[] | null = null;
    let turn: { text: string; toolBlocks: ToolBlock[]; thinkingBlocks: ThinkingBlockData[]; diffs: DiffEntry[] } | null = null;
    const flush = () => {
      if (turn && (turn.text || turn.toolBlocks.length || turn.thinkingBlocks.length || turn.diffs.length)) {
        result.push({ role: 'assistant', content: turn.text, toolBlocks: turn.toolBlocks, thinking: '', thinkingBlocks: turn.thinkingBlocks, diffs: turn.diffs });
      }
      turn = null;
    };

    for (const msg of rawMessages) {
      if (msg.role === 'toolResult') {
        const pending = turn?.toolBlocks.find((tb) => tb.result === null);
        if (pending) { pending.result = msg.text ?? ''; pending.isError = msg.isError === true; }
        if (msg.toolName === 'todo') {
          const phases = parseTodoPhases(msg.details);
          if (phases) latestTodos = phases;
        }
        continue;
      }
      if (msg.role === 'diff') {
        if (!turn) turn = { text: '', toolBlocks: [], thinkingBlocks: [], diffs: [] };
        turn.diffs.push({ filePath: msg.filePath ?? '', relPath: msg.relPath ?? '', diff: msg.diff ?? '' });
        continue;
      }
      if (msg.role === 'user') {
        flush();
        result.push({ role: 'user', content: msg.text ?? '', toolBlocks: [], thinking: '', thinkingBlocks: [], diffs: [] });
        continue;
      }
      if (!turn) turn = { text: '', toolBlocks: [], thinkingBlocks: [], diffs: [] };
      if (msg.thinkingBlocks?.length) {
        turn.thinkingBlocks.push(...msg.thinkingBlocks);
      } else if (msg.thinking) {
        turn.thinkingBlocks.push({ thinking: msg.thinking, duration: 0 });
      }
      if (msg.text) turn.text += (turn.text ? '\n\n' : '') + msg.text;
      for (const tc of msg.toolCalls ?? []) {
        turn.toolBlocks.push({ id: `h${toolCounter++}`, toolName: tc.toolName, args: tc.args, result: null, isError: false });
      }
    }
    flush();

    setMessages(result);
    setTodos(latestTodos ?? []);
    const seedCost = initialUsage?.costUsd ?? 0;
    costRef.current = seedCost;
    setUsage({
      inputTokens: initialUsage?.input ?? 0,
      outputTokens: initialUsage?.output ?? 0,
      cacheReadTokens: 0,
      cacheWriteTokens: 0,
      contextTokens: initialUsage?.totalTokens ?? 0,
      costUsd: seedCost,
    });
  }, []);

  return {
    messages, streaming, streamingTools, streamingDiffs, thinking, busy, error, sessionId, todos, usage,
    planMode, docType, planRows, pendingDocument,
    send, cancel, reset, loadHistory,
    setPlanMode, setDocType, togglePlanItem, generateDocument, clearPendingDocument,
  };
}
